apiVersion: v1
kind: Service
metadata:
  name: tc-svc
  namespace: {{ .Values.deployment.namespace }} 
spec:
  type: {{ .Values.service.type}}
  ports:
  - port: {{ .Values.service.clusterIPPort }}
    targetPort: {{ .Values.service.targetPort}}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: tc_webapp